//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgeMapFixer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForgeMapFixer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34A4,34A4
        ///2EB3,2EB3
        ///2EB4,2EB4
        ///2EBC,2EBC
        ///34A5,34A5
        ///34C1,34C1
        ///2EB1,2EB1
        ///2EAF,2EAF
        ///34A7,34A7
        ///34A8,34A8
        ///34A9,34A9
        ///4225,4225
        ///34AB,34AB
        ///2EBF,2EBF
        ///2EBE,2EBE
        ///34A6,34A6
        ///2EBA,2EBA
        ///2EBB,2EBB
        ///2EB5,2EB5
        ///2EB6,2EB6
        ///2EB2,2EB2
        ///2EBD,2EBD
        ///2EB0,2EB0
        ///2EB8,2EB8
        ///2EB9,2EB9
        ///444A,444A
        ///34C0,34C0
        ///34C2,34C2
        ///27EF,27EF
        ///34C5,34C5
        ///444B,444B
        ///34AA,34AA
        ///3FD4,3FD4
        ///4221,4221
        ///444C,444C
        ///4226,4226
        ///4224,4224
        ///3FD3,3FD3
        ///4220,4220
        ///4223,4223
        ///3FD6,3FD6
        ///3FD5,3FD5
        ///3A94,3A94
        ///2EE5,2EE5
        ///3A9E,3A9E
        ///4222,4222
        ///2EB7,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgeTagMap {
            get {
                return ResourceManager.GetString("ForgeTagMap", resourceCulture);
            }
        }
    }
}
